apiVersion: v1
data:
  kc-ispn.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <infinispan
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:infinispan:config:14.0 http://www.infinispan.org/schemas/infinispan-config-14.0.xsd"
            xmlns="urn:infinispan:config:14.0">

       <cache-container name="keycloak">
          <transport cluster="kubernetes">
                <properties>
                    <property name="configurationFile" value="default-configs/default-jgroups-kubernetes.xml"/>
                </properties>
            </transport>

          <local-cache name="realms">
             <encoding>
                <key media-type="application/x-java-object" />
                <value media-type="application/x-java-object" />
             </encoding>
             <memory max-count="10000" />
          </local-cache>
          <local-cache name="users">
             <encoding>
                <key media-type="application/x-java-object" />
                <value media-type="application/x-java-object" />
             </encoding>
             <memory max-count="10000" />
          </local-cache>
          <local-cache name="authorization">
             <encoding>
                <key media-type="application/x-java-object" />
                <value media-type="application/x-java-object" />
             </encoding>
             <memory max-count="10000" />
          </local-cache>
          <local-cache name="keys">
             <encoding>
                <key media-type="application/x-java-object" />
                <value media-type="application/x-java-object" />
             </encoding>
             <expiration max-idle="3600000" />
             <memory max-count="1000" />
          </local-cache>
          <distributed-cache name="sessions" owners="1">
             <persistence passivation="false">
                <remote-store xmlns="urn:infinispan:config:store:remote:14.0" cache="sessions" purge="false" preload="false" segmented="false" shared="true" raw-values="true" >
                    <remote-server host="${env.KEYCLOAK_CACHE_REMOTE_HOST}" port="11222" />
                    <security>
                       <authentication server-name="${env.KEYCLOAK_CACHE_REMOTE_HOST}">
                          <digest username="${env.KEYCLOAK_CACHE_REMOTE_USERNAME}" password="${env.KEYCLOAK_CACHE_REMOTE_PASSWORD}" realm="default" />
                       </authentication>
                    </security>
                     <!-- <property name="marshaller">org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory</property> -->
                 </remote-store>
             </persistence>
          </distributed-cache>
          <distributed-cache name="authenticationSessions" owners="1">
             <persistence passivation="false">
                <remote-store xmlns="urn:infinispan:config:store:remote:14.0" cache="authenticationSessions" purge="false" preload="false" segmented="false" shared="true" raw-values="true" >
                    <remote-server host="${env.KEYCLOAK_CACHE_REMOTE_HOST}" port="11222" />
                    <security>
                       <authentication server-name="${env.KEYCLOAK_CACHE_REMOTE_HOST}">
                          <digest username="${env.KEYCLOAK_CACHE_REMOTE_USERNAME}" password="${env.KEYCLOAK_CACHE_REMOTE_PASSWORD}" realm="default" />
                       </authentication>
                    </security>
                     <!-- <property name="marshaller">org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory</property> -->
                 </remote-store>
             </persistence>
          </distributed-cache>
          <distributed-cache name="offlineSessions" owners="1">
            <persistence passivation="false">
                <remote-store xmlns="urn:infinispan:config:store:remote:14.0" cache="offlineSessions" purge="false" preload="false" segmented="false" shared="true" raw-values="true" >
                    <remote-server host="${env.KEYCLOAK_CACHE_REMOTE_HOST}" port="11222" />
                    <security>
                       <authentication server-name="${env.KEYCLOAK_CACHE_REMOTE_HOST}">
                          <digest username="${env.KEYCLOAK_CACHE_REMOTE_USERNAME}" password="${env.KEYCLOAK_CACHE_REMOTE_PASSWORD}" realm="default" />
                       </authentication>
                    </security>
                  <!-- <property name="marshaller">org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory</property> -->
                 </remote-store>
            </persistence>
          </distributed-cache>
          <distributed-cache name="clientSessions" owners="1">
             <persistence passivation="false">
                <remote-store xmlns="urn:infinispan:config:store:remote:14.0" cache="clientSessions" purge="false" preload="false" segmented="false" shared="true" raw-values="true" >
                    <remote-server host="${env.KEYCLOAK_CACHE_REMOTE_HOST}" port="11222" />
                    <security>
                       <authentication server-name="${env.KEYCLOAK_CACHE_REMOTE_HOST}">
                          <digest username="${env.KEYCLOAK_CACHE_REMOTE_USERNAME}" password="${env.KEYCLOAK_CACHE_REMOTE_PASSWORD}" realm="default" />
                       </authentication>
                    </security>
                     <!-- <property name="marshaller">org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory</property> -->
                 </remote-store>
             </persistence>
          </distributed-cache>
          <distributed-cache name="offlineClientSessions" owners="1">
             <persistence passivation="false">
                <remote-store xmlns="urn:infinispan:config:store:remote:14.0" cache="offlineClientSessions" purge="false" preload="false" segmented="false" shared="true" raw-values="true" >
                    <remote-server host="${env.KEYCLOAK_CACHE_REMOTE_HOST}" port="11222" />
                    <security>
                       <authentication server-name="${env.KEYCLOAK_CACHE_REMOTE_HOST}">
                          <digest username="${env.KEYCLOAK_CACHE_REMOTE_USERNAME}" password="${env.KEYCLOAK_CACHE_REMOTE_PASSWORD}" realm="default" />
                       </authentication>
                    </security>
                     <!-- <property name="marshaller">org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory</property> -->
                 </remote-store>
             </persistence>
          </distributed-cache>
          <distributed-cache name="loginFailures" owners="1">
             <persistence passivation="false">
                <remote-store xmlns="urn:infinispan:config:store:remote:14.0" cache="loginFailures" purge="false" preload="false" segmented="false" shared="true" raw-values="true" >
                    <remote-server host="${env.KEYCLOAK_CACHE_REMOTE_HOST}" port="11222" />
                    <security>
                       <authentication server-name="${env.KEYCLOAK_CACHE_REMOTE_HOST}">
                          <digest username="${env.KEYCLOAK_CACHE_REMOTE_USERNAME}" password="${env.KEYCLOAK_CACHE_REMOTE_PASSWORD}" realm="default" />
                       </authentication>
                    </security>
                     <!-- <property name="marshaller">org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory</property> -->
                 </remote-store>
             </persistence>
          </distributed-cache>
          <distributed-cache name="actionTokens" owners="1">
             <expiration max-idle="-1" interval="300000" />
             <persistence passivation="false">
                <remote-store xmlns="urn:infinispan:config:store:remote:14.0" cache="actionTokens" purge="false" preload="false" segmented="false" shared="true" raw-values="true" >
                    <remote-server host="${env.KEYCLOAK_CACHE_REMOTE_HOST}" port="11222" />
                    <security>
                       <authentication server-name="${env.KEYCLOAK_CACHE_REMOTE_HOST}">
                          <digest username="${env.KEYCLOAK_CACHE_REMOTE_USERNAME}" password="${env.KEYCLOAK_CACHE_REMOTE_PASSWORD}" realm="default" />
                       </authentication>
                    </security>
                     <!-- <property name="marshaller">org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory</property> -->
                 </remote-store>
             </persistence>
          </distributed-cache>
          <replicated-cache name="work">
             <persistence passivation="false">
                <remote-store xmlns="urn:infinispan:config:store:remote:14.0" cache="work" purge="false" preload="false" segmented="false" shared="true" raw-values="true" >
                    <remote-server host="${env.KEYCLOAK_CACHE_REMOTE_HOST}" port="11222" />
                    <security>
                       <authentication server-name="${env.KEYCLOAK_CACHE_REMOTE_HOST}">
                          <digest username="${env.KEYCLOAK_CACHE_REMOTE_USERNAME}" password="${env.KEYCLOAK_CACHE_REMOTE_PASSWORD}" realm="default" />
                       </authentication>
                    </security>
                     <!-- <property name="marshaller">org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory</property> -->
                 </remote-store>
             </persistence>
          </replicated-cache>
       </cache-container>
    </infinispan>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: keycloak-cache-config
