apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak
          args: ["start-dev", "--cache-config-file=cache-ispn.xml", "--spi-connections-infinispan-quarkus-site-name='keycloak'"]
          env:
              # Turn on infinispan remote cache and service discovery in developer mode
            - name: KC_CACHE
              value: ispn
              # Set the transport layer stack to kubernetes
            - name: KC_CACHE_STACK
              value: kubernetes
              # set the dns.query to target the service name infinispan, to allow service discovery
            - name: JAVA_OPTS_APPEND
              value: "-Djgroups.dns.query=infinispan.default.svc.cluster.local"

              # Variables used to set the target server and authentication for remote cache stores
            - name: KEYCLOAK_CACHE_REMOTE_HOST
              value: infinispan
            - name: KEYCLOAK_CACHE_REMOTE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: infinispan-credentials
                  key: username
            - name: KEYCLOAK_CACHE_REMOTE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infinispan-credentials
                  key: password
  

            # keycloak credentials
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: password
            
              # keycloak database variables
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: postgres
            - name: KC_DB_URL_DATABASE
              value: keycloak_db
            - name: KC_DB_USERNAME
              valueFrom:
                  secretKeyRef:
                    name: postgres-credentials
                    key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          volumeMounts:
            - name: "keycloak-config-volume"
              mountPath: "/opt/keycloak/conf/cache-ispn.xml"
              subPath: "kc-ispn.xml"
          ports:
            - name: http
              containerPort: 8080
            - name: kc-infinispan
              containerPort: 11222
            - name: infini-jgroup
              containerPort: 7800
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          resources:
            requests:
              cpu: "300m"  # 300 milliCPU (0.3 CPU)
              memory: "128Mi"  # 128 Mebibytes
            limits:
              cpu: "500m"  # 500 milliCPU (0.5 CPU)
              memory: "512Mi"  # 512 Mebibytes
      volumes:
        - name: keycloak-config-volume
          configMap:
            name: keycloak-cache-config